// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5RTTO_avBdgLSnMVQIy6js82ZCqXCKHw',
    appId: '1:468825058349:web:f5e3a038a63de79d34dca4',
    messagingSenderId: '468825058349',
    projectId: 'chat-nabil',
    authDomain: 'chat-nabil.firebaseapp.com',
    storageBucket: 'chat-nabil.appspot.com',
    measurementId: 'G-4MBK0S9LKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtk759M8DB5HBg-_Sj2Tl5RAdcWFK5f18',
    appId: '1:468825058349:android:9a8abfa5acda298234dca4',
    messagingSenderId: '468825058349',
    projectId: 'chat-nabil',
    storageBucket: 'chat-nabil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURBU96b9jJ_wN5E8NCeUZAOe9p6EW_EI',
    appId: '1:468825058349:ios:e7580525b74f80e434dca4',
    messagingSenderId: '468825058349',
    projectId: 'chat-nabil',
    storageBucket: 'chat-nabil.appspot.com',
    iosBundleId: 'com.example.chatUdemy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURBU96b9jJ_wN5E8NCeUZAOe9p6EW_EI',
    appId: '1:468825058349:ios:ddb8d4881ea4cd9434dca4',
    messagingSenderId: '468825058349',
    projectId: 'chat-nabil',
    storageBucket: 'chat-nabil.appspot.com',
    iosBundleId: 'com.example.chatUdemy.RunnerTests',
  );
}
